2021-06-21 13:22:06,310 INFO    Thread-2  :874324 [wandb_setup.py:_flush():69] setting env: {'entity': 'naddeok', 'project': 'ECG Heartbeat Verifier', 'root_dir': '/home/naddeok5/HeartBreaker', 'sweep_id': 'rtewee01', 'run_id': '9wp8vzwq', 'sweep_param_path': '/home/naddeok5/HeartBreaker/wandb/sweep-rtewee01/config-9wp8vzwq.yaml'}
2021-06-21 13:22:06,310 INFO    Thread-2  :874324 [wandb_setup.py:_flush():69] setting login settings: {}
2021-06-21 13:22:06,311 INFO    Thread-2  :874324 [wandb_init.py:_log_setup():336] Logging user logs to /home/naddeok5/HeartBreaker/wandb/run-20210621_132206-9wp8vzwq/logs/debug.log
2021-06-21 13:22:06,311 INFO    Thread-2  :874324 [wandb_init.py:_log_setup():337] Logging internal logs to /home/naddeok5/HeartBreaker/wandb/run-20210621_132206-9wp8vzwq/logs/debug-internal.log
2021-06-21 13:22:06,311 INFO    Thread-2  :874324 [wandb_init.py:init():369] calling init triggers
2021-06-21 13:22:06,311 INFO    Thread-2  :874324 [wandb_init.py:init():374] wandb.init called with sweep_config: {'batch_size': 224, 'criterion': 'binary_cross_entropy', 'epochs': 1000000, 'learning_rate': 0.010757404946818093, 'momentum': 0.9, 'optimizer': 'adam', 'scheduler': 'Cosine Annealing', 'use_SAM': False, 'weight_decay': 1e-05}
config: {'epochs': 10000.0, 'batch_size': 1, 'momentum': 0.9, 'weight_decay': 1e-05, 'learning_rate': 1e-05, 'optimizer': 'adam', 'scheduler': 'Cosine Annealing', 'criterion': 'binary_cross_entropy', 'use_SAM': False}
2021-06-21 13:22:06,311 INFO    Thread-2  :874324 [wandb_init.py:init():418] starting backend
2021-06-21 13:22:06,311 INFO    Thread-2  :874324 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-06-21 13:22:06,324 INFO    Thread-2  :874324 [backend.py:ensure_launched():132] starting backend process...
2021-06-21 13:22:06,336 INFO    Thread-2  :874324 [backend.py:ensure_launched():136] started backend process with pid: 874546
2021-06-21 13:22:06,338 INFO    Thread-2  :874324 [wandb_init.py:init():423] backend started and connected
2021-06-21 13:22:06,339 INFO    Thread-2  :874324 [wandb_run.py:_config_callback():787] config_cb None None {'batch_size': 224, 'criterion': 'binary_cross_entropy', 'epochs': 1000000, 'learning_rate': 0.010757404946818093, 'momentum': 0.9, 'optimizer': 'adam', 'scheduler': 'Cosine Annealing', 'use_SAM': False, 'weight_decay': 1e-05}
2021-06-21 13:22:06,340 INFO    Thread-2  :874324 [wandb_init.py:init():465] updated telemetry
2021-06-21 13:22:06,342 INFO    Thread-2  :874324 [wandb_init.py:init():484] communicating current version
2021-06-21 13:22:07,437 INFO    Thread-2  :874324 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.32 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-06-21 13:22:07,437 INFO    Thread-2  :874324 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-06-21 13:22:07,569 INFO    Thread-2  :874324 [wandb_init.py:init():522] starting run threads in backend
2021-06-21 13:22:08,962 INFO    Thread-2  :874324 [wandb_run.py:_console_start():1565] atexit reg
2021-06-21 13:22:08,963 INFO    Thread-2  :874324 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-06-21 13:22:08,963 INFO    Thread-2  :874324 [wandb_run.py:_redirect():1417] Redirecting console.
2021-06-21 13:22:08,965 ERROR   Thread-2  :874324 [wandb_run.py:_redirect():1482] Failed to redirect.
Traceback (most recent call last):
  File "/home/naddeok5/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1475, in _redirect
    out_redir.install()
  File "/home/naddeok5/.local/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 605, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/naddeok5/.local/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 555, in add_fd
    self._register()
  File "/home/naddeok5/.local/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 540, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/usr/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2021-06-21 13:22:08,967 INFO    Thread-2  :874324 [wandb_init.py:init():546] run started, returning control to user process
2021-06-22 13:40:34,498 ERROR   Thread-1  :874324 [internal_api.py:execute():130] 502 response executing GraphQL.
2021-06-22 13:40:34,500 ERROR   Thread-1  :874324 [internal_api.py:execute():131] 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

