2021-06-19 22:26:34,285 INFO    Thread-5771:2727604 [wandb_setup.py:_flush():69] setting env: {'entity': 'naddeok', 'project': 'ECG Heartbeat Verifier', 'root_dir': '/home/naddeok5/HeartBreaker', 'run_id': 'umyz1dt5', 'sweep_param_path': '/home/naddeok5/HeartBreaker/wandb/sweep-gq8mwnhp/config-umyz1dt5.yaml', 'sweep_id': 'gq8mwnhp'}
2021-06-19 22:26:34,285 INFO    Thread-5771:2727604 [wandb_setup.py:_flush():69] setting login settings: {}
2021-06-19 22:26:34,285 INFO    Thread-5771:2727604 [wandb_init.py:_log_setup():336] Logging user logs to /home/naddeok5/HeartBreaker/wandb/run-20210619_222634-umyz1dt5/logs/debug.log
2021-06-19 22:26:34,285 INFO    Thread-5771:2727604 [wandb_init.py:_log_setup():337] Logging internal logs to /home/naddeok5/HeartBreaker/wandb/run-20210619_222634-umyz1dt5/logs/debug-internal.log
2021-06-19 22:26:34,285 INFO    Thread-5771:2727604 [wandb_init.py:init():369] calling init triggers
2021-06-19 22:26:34,285 INFO    Thread-5771:2727604 [wandb_init.py:init():374] wandb.init called with sweep_config: {'batch_size': 56, 'criterion': 'binary_cross_entropy', 'epochs': 595, 'learning_rate': 0.022169983564881108, 'momentum': 0.9, 'optimizer': 'adam', 'scheduler': None, 'use_SAM': False, 'weight_decay': 1e-05}
config: {'epochs': 20, 'batch_size': 1, 'momentum': 0.9, 'weight_decay': 1e-05, 'learning_rate': 1e-05, 'optimizer': 'adam', 'scheduler': 'Cosine Annealing', 'criterion': 'binary_cross_entropy', 'use_SAM': True}
2021-06-19 22:26:34,285 INFO    Thread-5771:2727604 [wandb_init.py:init():418] starting backend
2021-06-19 22:26:34,286 INFO    Thread-5771:2727604 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-06-19 22:26:34,289 INFO    Thread-5771:2727604 [backend.py:ensure_launched():132] starting backend process...
2021-06-19 22:26:34,329 INFO    Thread-5771:2727604 [backend.py:ensure_launched():136] started backend process with pid: 597571
2021-06-19 22:26:34,331 INFO    Thread-5771:2727604 [wandb_init.py:init():423] backend started and connected
2021-06-19 22:26:34,332 INFO    Thread-5771:2727604 [wandb_run.py:_config_callback():787] config_cb None None {'batch_size': 56, 'criterion': 'binary_cross_entropy', 'epochs': 595, 'learning_rate': 0.022169983564881108, 'momentum': 0.9, 'optimizer': 'adam', 'scheduler': None, 'use_SAM': False, 'weight_decay': 1e-05}
2021-06-19 22:26:34,333 INFO    Thread-5771:2727604 [wandb_init.py:init():465] updated telemetry
2021-06-19 22:26:34,334 INFO    Thread-5771:2727604 [wandb_init.py:init():484] communicating current version
2021-06-19 22:26:35,513 INFO    Thread-5771:2727604 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.32 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-06-19 22:26:35,514 INFO    Thread-5771:2727604 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-06-19 22:26:35,636 INFO    Thread-5771:2727604 [wandb_init.py:init():522] starting run threads in backend
2021-06-19 22:26:37,009 INFO    Thread-5771:2727604 [wandb_run.py:_console_start():1565] atexit reg
2021-06-19 22:26:37,010 INFO    Thread-5771:2727604 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-06-19 22:26:37,010 INFO    Thread-5771:2727604 [wandb_run.py:_redirect():1417] Redirecting console.
2021-06-19 22:26:37,010 ERROR   Thread-5771:2727604 [wandb_run.py:_redirect():1482] Failed to redirect.
Traceback (most recent call last):
  File "/home/naddeok5/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1475, in _redirect
    out_redir.install()
  File "/home/naddeok5/.local/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 605, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/naddeok5/.local/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 555, in add_fd
    self._register()
  File "/home/naddeok5/.local/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 540, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/usr/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2021-06-19 22:26:37,010 INFO    Thread-5771:2727604 [wandb_init.py:init():546] run started, returning control to user process
2021-06-20 02:06:20,884 INFO    Thread-5771:2727604 [wandb_run.py:finish():1208] finishing run naddeok/ECG Heartbeat Verifier/umyz1dt5
